import express from "express";
import authRouter from "./auth";
import adminRouter from "./admin";
import userRouter from "./user";
import usersRouter from "./users";
import scheduleRouter from "./schedule";
import settingsRouter from "./settings";
import checkInRouter from "./checkin";
import teamsRouter from "./teams";
import projectsRouter from "./projects";
import requestsRouter from "./requests";

const router = express.Router();
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/user", userRouter);
router.use("/users", usersRouter);
router.use("/schedule", scheduleRouter);
router.use("/settings", settingsRouter);
router.use("/teams", teamsRouter);
router.use("/requests", requestsRouter);
router.use("/check-in", checkInRouter);
router.use("/projects", projectsRouter);
export default router;
