import express from "express";
import authRouter from "./auth";
import adminRouter from "./admin";
import userRouter from "./user";
import usersRouter from "./users";
import scheduleRouter from "./schedule";
import settingsRouter from "./settings";
import checkInRouter from "./checkin";
import teamRouter from "./team";
import teamsRouter from "./teams";
import projectsRouter from "./projects";
import requestsRouter from "./requests";
import recruiterRouter from "./recruiter";
import sponsorRouter from "./sponsor";

const router = express.Router();
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/user", userRouter);
router.use("/users", usersRouter);
router.use("/schedule", scheduleRouter);
router.use("/settings", settingsRouter);
router.use("/team", teamRouter);
router.use("/teams", teamsRouter);
router.use("/requests", requestsRouter);
router.use("/check-in", checkInRouter);
router.use("/projects", projectsRouter);
router.use("/sponsor", sponsorRouter);
router.use("/recruiter", recruiterRouter);
export default router;
