export enum EmailGroup {
  PARTICIPANTS_VERIFIED = "PARTICIPANTS_VERIFIED",
  PARTICIPANTS_COMPLETED = "PARTICIPANTS_COMPLETED",
  PARTICIPANTS_CONFIRMED = "PARTICIPANTS_CONFIRMED",
  SPONSORS = "SPONSORS",
  ADMINS = "ADMINS",
}

export enum EmailStatus {
  QUEUED = "QUEUED",
  SENT = "SENT",
  ERROR = "ERROR",
  DELETED = "DELETED",
}
