name: Build & Test

on:
  push:
    branches: [main, refactor]
  pull_request:
    branches: [main, refactor]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_PORT: 465
      JWT_SECRET: "Hello World"
      AUTH_TOKEN_EXPIRY: "20d"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Build project
        run: |
          npm install
          npm run lint:only
          npm run build
