# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables
    env:
      EMAIL_PORT: 465
      JWT_SECRET: "Hello World"
      AUTH_TOKEN_EXPIRY: "20d"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build project
        run: |
          npm install
          npm run lint:only
          npm run build

      - name: Run tests
        run: |
          npm test

  coverage:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Build Project
        run: |
          npm install
          npm run build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 0e1282aa3a3381f8b403add1674c981483766b199d9ee55806bef31596851c7a
        with:
          coverageCommand: npm run test:coverage