name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_PORT: 465
      JWT_SECRET: "Hello World"
      AUTH_TOKEN_EXPIRY: "20d"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build project
        run: |
          npm install
          npm run lint:only
          npm run build
      - name: Run tests
        run: |
          npm run test:nodoppler
  coverage:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Build Project
        run: |
          npm install
          npm run build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 0e1282aa3a3381f8b403add1674c981483766b199d9ee55806bef31596851c7a
        with:
          coverageCommand: npm run test:coverage